### ISSUE TITLE
errors while trying newsClassifier.py

### ISSUE THREAD

**Issue by kp625544** [muatik/naive-bayes-classifier#7]
Traceback (most recent call last):
  File "newsClassifier.py", line 22, in <module>
    newsTrainer.train(news['text'], news['category'])
  File "/home/hydra/Desktop/AUR/projectSpider/naive-bayes-classifier/naiveBayesClassifier/trainer.py", line 17, in train
    tokens = self.tokenizer.tokenize(text)
AttributeError: 'module' object has no attribute 'tokenize'

**Comment by sriramsaiamuluru1** [comment]
Any one who can respond for the solution of the above mentioned issue?

**Comment by flamato** [comment]
Hello ! I had the same problem. 

To solve it, I installed anaconda for Python 2.7 and tried this command in the Anaconda prompt : 
`pip install naiveBayesClassifier`
